### ISSUE TITLE
requestParamsAttributes.params.find is not a function

### ISSUE THREAD

**Issue by yeganehaym** [moszeed/easysoap#48]
get all available methods and get their paramsinfo was successful
but call method gave met this error:

```
TypeError: requestParamsAttributes.params.find is not a function
    at getMethodParamRequestString (D:\projects\nodejs\irdomain\node_modules\easysoap\src\request.js:104:22)
    at getRequestParamsAsString (D:\projects\nodejs\irdomain\node_modules\easysoap\src\request.js:130:17)
```
this is mycode:
```
var query= {
            auth:{
                Webservice_id:this.username,
                Webservice_pass:this.password
            },
            domain:domain
        };
soapClient.call({
    method    : 'DomainInfo',
    attributes: {
       xmlns: this.host
    },
    params: query
 })
 .then((callResponse) => {
     console.log(callResponse.data);	// response data as json
     console.log(callResponse.body);	// response body
     console.log(callResponse.header);  //response header
 })
 .catch((err) => { console.log(err); });
```

**Comment by moszeed** [comment]
Hi, thx for reporting this, can yoy give a link to the used WSDL file ?

**Comment by moszeed** [comment]
should be fixed now, reinstall easysoap module (there was a bug in the used module "wsdlrdr") ..

**Comment by mikeiasbatista** [comment]
Hi!

I'm using the earliest version of, but getting the same error.
My code is pretty the same also, just a simple request.
